#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Render docs/rules.md, one heading per rule, from meta/oold-rules.json.

Why this exists: zensical builds the documentation site from Markdown under docs/, and only
indexes headings it renders itself. docs/spec/index.html is a self-contained ReSpec document
that zensical copies verbatim into the built site without indexing it - so a rule id such as
OOLD-RT-08f2, cited in a validator's report, was unfindable in the docs search pane. There was
no Markdown page and no heading for it to land on.

This script is the fix: it turns the generated rule catalogue into a Markdown page, one `###`
heading per rule, so zensical's search index gets one entry per rule id instead of zero. Run
from `make spec`, after scripts/extract_rules.py has produced meta/oold-rules.json.

The catalogue is the only source of truth here: this script does not re-derive anything from
spec/sections/*.md, it only reshapes what extract_rules.py already extracted.
"""

from __future__ import annotations

import json
import os
import re
import sys
from html import escape

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CATALOG = os.path.join(ROOT, "meta", "oold-rules.json")
OUT = os.path.join(ROOT, "docs", "rules.md")

BANNER = (
    "<!-- DO NOT EDIT - generated by scripts/render_rules_page.py from meta/oold-rules.json. "
    "Regenerate with `make spec`, do not edit this file by hand. -->"
)

LEAD = """A rule id such as `OOLD-RT-08f2` names one normative statement (a MUST, MUST NOT, SHOULD,
SHOULD NOT or REQUIRED) from the [OO-LD specification](spec/). Validators cite these ids in their
output, so a report that says a document fails `OOLD-RT-08f2` should let you find exactly what that
means - this page is where that lookup lands. Ids are permanent and never reused: a rule that is
retired stays on this page, marked deprecated, so an id from an old report still resolves to
something."""


#: A cross-reference to another part of the specification, as it survives into a rule's `text`.
#: ReSpec's form leaves the link text empty (`[](#round-trip)`) and fills it in client-side from
#: the target heading, which only works on the spec page itself.
XREF = re.compile(r"\[([^\]]*)\]\(#([A-Za-z0-9_-]+)\)")


def link_to_spec(text: str) -> str:
    """Repoint the specification's own cross-references at the specification.

    Left verbatim, they resolve against this page, where those headings do not exist: the site
    build reports six broken anchors and the empty-text ones render as invisible links. An empty
    link text becomes the section id, which is the only name for the target available here.

    Done at render time rather than in extract_rules.py's CLEAN list on purpose. Cleaning it
    there would change `text` for every affected rule, and `text_sha256` with it, which the
    baseline reads as six rules silently rewritten.
    """
    return XREF.sub(lambda m: f"[{m.group(1) or m.group(2)}](spec/#{m.group(2)})", text)


def anchor(rule_id: str) -> str:
    """The #fragment a heading `### <rule_id>` gets from the `toc` extension (permalink = true).

    The default slugify keeps word characters and hyphens as-is and only lowercases, so
    `OOLD-RT-08f2` becomes `oold-rt-08f2` - confirmed by inspecting a built site, not assumed.
    """
    return rule_id.lower()


def load_catalog() -> dict:
    try:
        with open(CATALOG, encoding="utf-8") as handle:
            raw = handle.read()
    except OSError as exc:
        print(f"cannot read {CATALOG}: {exc}", file=sys.stderr)
        sys.exit(1)
    try:
        catalog = json.loads(raw)
    except ValueError as exc:
        print(f"{CATALOG} is not valid JSON: {exc}", file=sys.stderr)
        sys.exit(1)
    try:
        catalog["areas"]
        catalog["rules"]
    except KeyError as exc:
        print(f"{CATALOG} is missing the {exc} key; nothing to render", file=sys.stderr)
        sys.exit(1)
    return catalog


#: What each property on an entry means. Defined once and used twice: as the legend table at the
#: top of the page, and as the tooltip on that property in every entry, so a reader forty rules
#: down does not have to scroll back up to remember what "Machine-checkable" claims.
PROPERTY_HELP = {
    "Level": (
        "The RFC 2119 keyword this requirement is stated with. A validator reports a MUST-level "
        "finding as a failure and a SHOULD-level one as a warning, so the level decides severity "
        "rather than the check that found it."
    ),
    "Applies to": (
        "Who the requirement binds: a document, an implementation of OO-LD, or nobody in "
        "particular. This decides what is even able to enforce it."
    ),
    "Machine-checkable": (
        "Whether a validator could decide this rule by inspecting a document. It does not say the "
        "OO-LD validator enforces it today - `oold rules list --unchecked` reports that."
    ),
    "Since": (
        "The specification release this rule first appeared in. Ids are permanent and never "
        "reused, so this does not change once recorded."
    ),
}


def plain(text: str) -> str:
    """Markdown stripped back to what a `title` attribute can show.

    A tooltip is plain text: backticks would appear as literal characters, so the same sentence
    that reads as code in the legend table has to lose them here.
    """
    return text.replace("`", "")


def labelled(name: str, value: str, value_help: str = "") -> str:
    """One property bullet, with its explanation on hover."""
    tip = escape(plain(PROPERTY_HELP[name]), quote=True)
    shown = f'<span title="{escape(plain(value_help), quote=True)}">{value}</span>' if value_help else value
    return f'- <strong title="{tip}">{name}:</strong> {shown}'


def render_legend(applies_to: dict[str, str]) -> str:
    """The same explanations as a table, once, at the top.

    `applies_to` comes from the catalogue rather than being restated here, so the page cannot
    disagree with the data it renders.
    """
    kinds = "; ".join(f"`{kind}` - {desc[0].lower() + desc[1:]}" for kind, desc in applies_to.items())
    rows = [
        "## How to read an entry",
        "",
        "Every rule below lists the same four properties. Hovering over a property name in an entry",
        "repeats the explanation, so you do not have to come back here.",
        "",
        "| Property | Meaning |",
        "| --- | --- |",
    ]
    for name, help_text in PROPERTY_HELP.items():
        meaning = help_text
        if name == "Applies to":
            meaning = f"{help_text} {kinds}."
        rows.append(f"| **{name}** | {meaning} |")
    rows.append("")
    return "\n".join(rows)


def render_rule(rule: dict, applies_to: dict[str, str]) -> str:
    lines = [f"### {rule['id']}", ""]

    if rule.get("deprecated"):
        note = "**Deprecated.**"
        superseded = rule.get("superseded_by") or []
        if superseded:
            links = ", ".join(f"[{sid}](#{anchor(sid)})" for sid in superseded)
            note += f" Superseded by {links}."
        lines.append(note)
        lines.append("")

    kind = rule["applies_to"]
    lines.append(labelled("Level", rule["level"]))
    lines.append(labelled("Applies to", kind, applies_to.get(kind, "")))
    lines.append(labelled("Machine-checkable", "yes" if rule.get("machine_checkable") else "no"))
    lines.append(labelled("Since", rule["since"]))
    lines.append("")

    lines.append(link_to_spec(rule["summary"]))
    lines.append("")

    lines.append(link_to_spec(rule["text"]))
    lines.append("")

    if rule.get("context") and rule["context"] != rule["text"]:
        lines.append("> **In context:** " + link_to_spec(rule["context"]))
        lines.append("")

    lines.append(
        f"See [this rule in the specification](spec/#{rule['id']}) (section: {rule['section']})."
    )
    lines.append("")
    return "\n".join(lines)


def render_area(code: str, description: str, rules: list[dict], applies_to: dict[str, str]) -> str:
    parts = [f"## {code} - {description}", ""]
    for rule in sorted(rules, key=lambda r: r["id"]):
        parts.append(render_rule(rule, applies_to))
    return "\n".join(parts)


def build() -> None:
    catalog = load_catalog()
    areas: dict[str, str] = catalog["areas"]
    rules: list[dict] = catalog["rules"]

    by_area: dict[str, list[dict]] = {code: [] for code in areas}
    for rule in rules:
        by_area.setdefault(rule["area"], []).append(rule)

    applies_to: dict[str, str] = catalog.get("applies_to", {})

    sections = [BANNER, "", "# Rule catalogue", "", LEAD, "", render_legend(applies_to)]
    for code, description in areas.items():
        if not by_area.get(code):
            continue
        sections.append(render_area(code, description, by_area[code], applies_to))

    text = "\n".join(sections)
    text = text.rstrip("\n") + "\n"
    # newline="\n": committed and compared byte-for-byte by the CI drift guard, so it must not
    # depend on the platform that generated it (same reasoning as extract_rules.py's OUT).
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)

    print(f"Wrote docs/rules.md ({len(rules)} rules)")


if __name__ == "__main__":
    build()
