#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Render docs/rules.md, one heading per rule, from meta/oold-rules.json.

Why this exists: zensical builds the documentation site from Markdown under docs/, and only
indexes headings it renders itself. docs/spec/index.html is a self-contained ReSpec document
that zensical copies verbatim into the built site without indexing it - so a rule id such as
OOLD-RT-08f2, cited in a validator's report, was unfindable in the docs search pane. There was
no Markdown page and no heading for it to land on.

This script is the fix: it turns the generated rule catalogue into a Markdown page, one `###`
heading per rule, so zensical's search index gets one entry per rule id instead of zero. Run
from `make spec`, after scripts/extract_rules.py has produced meta/oold-rules.json.

The catalogue is the only source of truth here: this script does not re-derive anything from
spec/sections/*.md, it only reshapes what extract_rules.py already extracted.
"""

from __future__ import annotations

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CATALOG = os.path.join(ROOT, "meta", "oold-rules.json")
OUT = os.path.join(ROOT, "docs", "rules.md")

BANNER = (
    "<!-- DO NOT EDIT - generated by scripts/render_rules_page.py from meta/oold-rules.json. "
    "Regenerate with `make spec`, do not edit this file by hand. -->"
)

LEAD = """A rule id such as `OOLD-RT-08f2` names one normative statement (a MUST, MUST NOT, SHOULD,
SHOULD NOT or REQUIRED) from the [OO-LD specification](spec/). Validators cite these ids in their
output, so a report that says a document fails `OOLD-RT-08f2` should let you find exactly what that
means - this page is where that lookup lands. Ids are permanent and never reused: a rule that is
retired stays on this page, marked deprecated, so an id from an old report still resolves to
something."""


#: A cross-reference to another part of the specification, as it survives into a rule's `text`.
#: ReSpec's form leaves the link text empty (`[](#round-trip)`) and fills it in client-side from
#: the target heading, which only works on the spec page itself.
XREF = re.compile(r"\[([^\]]*)\]\(#([A-Za-z0-9_-]+)\)")


def link_to_spec(text: str) -> str:
    """Repoint the specification's own cross-references at the specification.

    Left verbatim, they resolve against this page, where those headings do not exist: the site
    build reports six broken anchors and the empty-text ones render as invisible links. An empty
    link text becomes the section id, which is the only name for the target available here.

    Done at render time rather than in extract_rules.py's CLEAN list on purpose. Cleaning it
    there would change `text` for every affected rule, and `text_sha256` with it, which the
    baseline reads as six rules silently rewritten.
    """
    return XREF.sub(lambda m: f"[{m.group(1) or m.group(2)}](spec/#{m.group(2)})", text)


def anchor(rule_id: str) -> str:
    """The #fragment a heading `### <rule_id>` gets from the `toc` extension (permalink = true).

    The default slugify keeps word characters and hyphens as-is and only lowercases, so
    `OOLD-RT-08f2` becomes `oold-rt-08f2` - confirmed by inspecting a built site, not assumed.
    """
    return rule_id.lower()


def load_catalog() -> dict:
    try:
        with open(CATALOG, encoding="utf-8") as handle:
            raw = handle.read()
    except OSError as exc:
        print(f"cannot read {CATALOG}: {exc}", file=sys.stderr)
        sys.exit(1)
    try:
        catalog = json.loads(raw)
    except ValueError as exc:
        print(f"{CATALOG} is not valid JSON: {exc}", file=sys.stderr)
        sys.exit(1)
    try:
        catalog["areas"]
        catalog["rules"]
    except KeyError as exc:
        print(f"{CATALOG} is missing the {exc} key; nothing to render", file=sys.stderr)
        sys.exit(1)
    return catalog


def render_rule(rule: dict) -> str:
    lines = [f"### {rule['id']}", ""]

    if rule.get("deprecated"):
        note = "**Deprecated.**"
        superseded = rule.get("superseded_by") or []
        if superseded:
            links = ", ".join(f"[{sid}](#{anchor(sid)})" for sid in superseded)
            note += f" Superseded by {links}."
        lines.append(note)
        lines.append("")

    lines.append(f"- **Level:** {rule['level']}")
    lines.append(f"- **Applies to:** {rule['applies_to']}")
    lines.append(f"- **Checkable:** {'yes' if rule.get('checkable') else 'no'}")
    lines.append(f"- **Since:** {rule['since']}")
    lines.append("")

    lines.append(link_to_spec(rule["summary"]))
    lines.append("")

    lines.append(link_to_spec(rule["text"]))
    lines.append("")

    lines.append(
        f"See [this rule in the specification](spec/#{rule['id']}) (section: {rule['section']})."
    )
    lines.append("")
    return "\n".join(lines)


def render_area(code: str, description: str, rules: list[dict]) -> str:
    parts = [f"## {code} - {description}", ""]
    for rule in sorted(rules, key=lambda r: r["id"]):
        parts.append(render_rule(rule))
    return "\n".join(parts)


def build() -> None:
    catalog = load_catalog()
    areas: dict[str, str] = catalog["areas"]
    rules: list[dict] = catalog["rules"]

    by_area: dict[str, list[dict]] = {code: [] for code in areas}
    for rule in rules:
        by_area.setdefault(rule["area"], []).append(rule)

    sections = [BANNER, "", "# Rule catalogue", "", LEAD, ""]
    for code, description in areas.items():
        if not by_area.get(code):
            continue
        sections.append(render_area(code, description, by_area[code]))

    text = "\n".join(sections)
    text = text.rstrip("\n") + "\n"
    # newline="\n": committed and compared byte-for-byte by the CI drift guard, so it must not
    # depend on the platform that generated it (same reasoning as extract_rules.py's OUT).
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)

    print(f"Wrote docs/rules.md ({len(rules)} rules)")


if __name__ == "__main__":
    build()
